python src/conv_vae/train.py \
    --stat_phys_model percolation \
    --dataset_size 1024 \
    --save_dir ./saved_models/conv_vae \
    --epochs 32 \
    --learning_rate 1e-3 \
    --batch_size 32 \
    --reg_ratio 100.0 \
    --lattice_size 64 \
    --n_conv_cells 5 \
    --n_convt_cells 5 \
    --latent_dim 40 \
    --no-use_property \
    --save_checkpoints